name: oflutter
description: Optimizations for the original Flutter framework.
version: 0.0.0
resolution: workspace
repository: https://github.com/flutter/oflutter

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.8"

dependencies:
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
