name: oflutter
description: Optimizations for the original Flutter framework.
version: 0.0.0
resolution: workspace
repository: https://github.com/flutter/oflutter

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.8"

dependencies:
  analyzer: ^7.7.1
  args: ^2.7.0
  build: ^3.0.2
  flutter: { sdk: flutter }
  oflutter_anno: ^0.0.0
  oflutter_name: ^0.0.0
  source_gen: ^3.1.0

dev_dependencies:
  build_runner: ^2.7.0
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: false
