name: chat
description: A chat app as an example of the OFlutter framework.
version: 0.0.0+0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.8"

dependencies:
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: false
