name: oflutter_anno
description: Annotations for OFlutter related code generating.
version: 0.0.0
resolution: workspace
repository: https://github.com/oflutter/oflutter

environment:
  sdk: ^3.8.1

dependencies:
  meta: ^1.16.0
  oflutter_name: ^0.0.0

dev_dependencies:
  build_runner: ^2.7.0
