name: oflutter_name
description: Generate names, library identifiers, and type identifiers.
version: 0.0.0
resolution: workspace
repository: https://github.com/oflutter/oflutter

environment:
  sdk: ^3.8.1

dependencies:
  analyzer: ^7.7.1
  build: ^3.0.2
  meta: ^1.16.0
  source_gen: ^3.1.0

dev_dependencies:
  test: ^1.24.0
